### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by nevenRakonic** [fpiskur/zvjezdana#1]
Clients controller:
```
if params[:query].present?
      # Search first and last names or both
      @clients = Client.where("first_name || ' ' || last_name LIKE ?", "%#{params[:query].upcase}%").paginate(page: params[:page], per_page: 50)
    else
      @clients = Client.all.paginate(page: params[:page], per_page: 50)
    end
```

ovo bi ovako:

```
if params[:query].present?
      # Search first and last names or both
      @clients = Client.where("first_name || ' ' || last_name LIKE %?%", params[:query].upcase)
    else
      @clients = Client.all
    end
    @clients = @clients.paginate(page: params[:page], per_page: 50)
```
Mislim da je citljivije bez interpolacije i nisam ziher dal je moguca SQL injekcija ako interpoliras string koji passas u query params al u ovom slucaju smo sigurni da ne moze.
Takodjer poziv na paginaciju micemo jer se uvijek zove. Mozes i prebaciti metodu gdje querias na model, na ovako malom projektu je to ok. S vremenom se trebaju drugi patterni koristiti jer dodje do problema[ fat model](https://medium.com/@jaysadiq/refactoring-a-fat-rails-model-dc3cfda64d22)

[Ovo](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/controllers/clients_controller.rb#L39) i slicno mozes prebaciti u privatnu metodu na kontroleru jer se ponavlja par puta. Moguce je da logika fetchanja resursa postane kompleksnija, a ovako to imas u jednoj metodi izluceno.

[Ovdje](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/controllers/clients_controller.rb#L20) mozes zvati ```@clients.treatments``` u viewu, ne vidim potrebu za instance varijablom. Moguce isto i za ```@treatment```. Takodjer  ```.all``` poziv je redundatan - ne treba ti na active record relacijama.

[Create akcija](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/controllers/clients_controller.rb#L29) 
```flash[:danger] = "Greška prilikom dodavanja novog klijenta! - #{@client.errors.full_messages.to_sentence}"```
Ovo je dovoljno, ako ```save``` vrati false errors nece biti prazan jer je neka validacija pala. Takodjer mozes koristiti ```save!``` pa imati rescue block za errore na razini kontrolera (tako je lakse globalno rjesiti error handling umjesto da stalno po kontrolerskim akcijama setiras flash message), al o tom potom.

[Hardkodirane informacije](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/helpers/sessions_helper.rb#L38) je najbolje spremiti u ENV varijablu ili jos bolje [enkriptirani credentialsi](https://web-crunch.com/posts/the-complete-guide-to-ruby-on-rails-encrypted-credentials) jer mi se ovo cini da bi mogao biti security issue.

[Class method](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/models/user.rb#L10) deifniras sa ```self.ime_metode```. S tvojim pristupom ako preimenujes model, moras se sjetiti mjenjati i definicije svih tih metoda.

[Client model](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/models/client.rb#L10) Ovdje bi preporucio guard clause i izbjegavanje unless ako imas vise od jednog uvjeta (teze je razmisljati s negativnom logikom)
```
 def first_name_or_last_name
   return if first_name.blank && last.name.blank?
   errors.add(:base, "Ispunite barem jedno od polja - Ime ili Prezime.")
 end
 ```
Jako preporucam [Rubocop](https://github.com/rubocop/rubocop) koji bi te na dosta ovakvih stvario automatski upozorio - mozes ga koristiti unutar VS Codea.

[Default scope](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/models/treatment.rb#L3) na modelu [nije dobra ideja](https://stackoverflow.com/questions/25087336/why-is-using-the-rails-default-scope-often-recommend-against)

[Validacije](https://github.com/fpiskur/zvjezdana/blob/b124afe3d0d1c0006cfa496c34c2ce2446e8afbe/app/models/treatment.rb#L4) Nema potrebe validirati dva atributa u jednoj metodi, mozes validirati svaki zasebno.
```validates :client_id, :description, :date, presence: true```. Slicno i na ```Client``` modelu. Takodjer za ```date``` bi preporucio dodatne validacije tipa da ne moze u proslost i slicno. Takodjer u railsima je konvencija da vremenski fieldovi zavrse na ```_at```. Nesto tipa ```scheduled_at``` bi imalo vise smisla posto pretpostavljam da nije samo datum nego je i vrijeme + datum.

**Comment by fpiskur** [comment]
@nevenRakonic vidi sad. Jedino za ove validacije na kraju u client modelu nisam našao alternativu budući da imam conditional validation.
